---
$:
  preprocess:
    '$.e2e.wait.uri.0': 'eval'
  npm:
    scripts: []                                                             # Scripts to run after installing dependencies
  emit:
    pattern:                                                                # Files to include
      - /.+\.e2e\.js$/i
    ignore:                                                                 # Files to exclude
      - /^(.*\/)?node_modules(\/?$)?/i
  test:
    mocha:
      options:                                                              # Mocha options
        ui: 'bdd'
        reporter: 'spec'
    pattern:                                                                # Files to include
      - /.+\.spec\.js$/i
    ignore: ~                                                               # Files to exclude
  e2e:
    pattern:
      - /.+\.e2e\.js$/i
    ignore: []
    browsers: 
      - puppeteer
    wait:
      interval: 500
      timeout: 60000
      uri:
        - 'process.env.DEPLOY_HOST'
www:
  root: 'test/suite'
  dependencies:
    chance: 'latest'
